### ISSUE TITLE
Failure on cf push

### ISSUE THREAD

**Issue by yurikoex** [IBM-Cloud/aspnet-core-helloworld#12]
Any idea from the logs what is the issue?

Logs:
Creating container
Successfully created container
Downloading app package...
Downloaded app package (21.5K)
Staging...
ASP.NET 5 buildpack version: 0.7.0
ASP.NET 5 buildpack starting compile
-----> Restoring files from buildpack cache
       OK
-----> Extracting libuv
       libuv version: 1.4.2
       OK
-----> Extracting libunwind
       libunwind version: 1.1
       OK
-----> Installing DNVM
       Downloading dnvm as script to '/tmp/app/.dnx/dnvm'

```
   Appending source string to /tmp/app/.bashrc
   Type 'source /tmp/app/.dnx/dnvm/dnvm.sh' to start using dnvm
   OK
```

-----> Installing DNX with DNVM
       Downloading dnx-coreclr-linux-x64.1.0.0-rc1-final from https://www.nuget.org/api/v2
       Download: https://www.nuget.org/api/v2/package/dnx-coreclr-linux-x64/1.0.0-rc1-final
###### ################################################################## 100.0%

```
   Installing to /tmp/app/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-final
   Adding /tmp/app/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-final/bin to process PATH
   Setting alias 'default' to 'dnx-coreclr-linux-x64.1.0.0-rc1-final'
   OK
```

-----> Restoring dependencies with DNU
       Adding /tmp/app/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-final/bin to process PATH
       Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16202

```
   Restoring packages for /tmp/app/src/dotnetstarter/project.json
   Warning: FindPackagesById: Microsoft.AspNet.Server.Kestrel
     The value cannot be null or empty.
   Parameter name: UserName
   Warning: FindPackagesById: Microsoft.AspNet.Server.Kestrel
     The value cannot be null or empty.
   Parameter name: UserName
   Error: FindPackagesById: Microsoft.AspNet.Server.Kestrel
     The value cannot be null or empty.
   Parameter name: UserName
   Warning: FindPackagesById: Microsoft.AspNet.StaticFiles
     The value cannot be null or empty.
   Parameter name: UserName
   Warning: FindPackagesById: Microsoft.AspNet.StaticFiles
     The value cannot be null or empty.
   Parameter name: UserName
   Error: FindPackagesById: Microsoft.AspNet.StaticFiles
     The value cannot be null or empty.
   Parameter name: UserName
   ----------
   System.ArgumentException: The value cannot be null or empty.
   Parameter name: UserName
      at System.Net.Http.CurlHandler.EasyRequest.SetProxyOptions(Uri requestUri)
      at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
      at System.Net.Http.CurlHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource.<GetAsync>d__11.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.Restore.NuGet.NuGetv2Feed.<FindPackagesByIdAsyncCore>d__25.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibrary>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
      at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
      at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
   ----------
   Restore failed
   The value cannot be null or empty.
   Parameter name: UserName
   FAILED: command failed, exit status 1
   FAILED: Restoring dependencies with DNU failed, command failed, exit status 1
```

Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
BuildpackCompileFailed

**Comment by opiethehokie** [comment]
Are you behind an authenticated proxy?

**Comment by yurikoex** [comment]
I am behind a proxy, which is most likely the issue. Not sure what URL's to chase up

**Comment by opiethehokie** [comment]
I found https://github.com/aspnet/dnx/issues/451 which makes it look like a dnx bug that still exists in RC1.

**Comment by opiethehokie** [comment]
@JTLunsford it seems that this should be working now that the buildpack has switched to using the dotnet CLI. Any chance you can confirm it works in your CF?
